### ISSUE TITLE
Sans erreur mais ne fonctionne pas

### ISSUE THREAD

**Issue by anterta** [ABOATDev/Control-Google-Home#2]
L'installation c'est entièrement bien passé, lorsque je demande à mon google home une action elle arrive bien jusqu'à mon pc :
[assistant] Assistant v2.0.5 : Chargement en cours...
[assistant] 4 plugins trouvés.
[assistant] Chargement du plugin 'control-windows' (v1.0.0)
[assistant-control-windows] Plugin chargé et prêt.
[assistant] Chargement du plugin 'ifttt' (v2.0.0)
[assistant-ifttt] Plugin chargé et prêt.
[assistant] Chargement du plugin 'launch' (v1.0.1)
[assistant-launch] Plugin chargé et prêt.
[assistant] Chargement du plugin 'notifier' (v2.1.0)
[assistant-notifier] Plugin chargé et prêt.
[assistant] Prêt à écouter les commandes via PushBullet
[assistant] Commande reçue: [ 'launch_"C:\GoogleHome\GoogleHome.vbs" coupe le son' ]
[assistant] Appelle du plugin 'launch'

Mais rien ne passe après...

**Comment by ABOATDev** [comment]
Salut, 
Le fichier GoogleHome.vbs  (https://github.com/ABOATDev/Control-Google-Home/blob/master/GoogleHome.vbs) se trouve bien dans C:\GoogleHome\GoogleHome.vbs ?

Puis ouvre le fichier GoogleHome.vbs et tape : test
Et renvoie moi le résultat

**Comment by anterta** [comment]
![capture](https://user-images.githubusercontent.com/26244683/44907778-6bd97080-ad19-11e8-9c57-bc3cd67ec700.PNG)

**Comment by anterta** [comment]
tout est OK...

**Comment by ABOATDev** [comment]
Bonsoir, j'ai trouvé la solution (le problème était pour tout le monde)
Télécharger l'archive : https://bayfiles.com/96xaNagaba/assistant-plugins_zip
Et remplacer les 6 fichiers -> http://prntscr.com/kpt38f http://prntscr.com/kpt3pc 
Assistant-plugins a fait une mise a jours
