### ISSUE TITLE
Google HOME - PC windows 10 - ne fonctionne pas

### ISSUE THREAD

**Issue by jdenieul** [ABOATDev/Control-Google-Home#3]
Bonjour,

Après avoir tout installé, je reçois bien les notifications de votre programme, exemple : 
 "Ok Google, sur le pc lancer google chrome"
 "Je reçois une notification sur le PC"
Mais rien ne se passe.

Je fais ensuite les commandes "OK google, sur le pc TEST" mais rien ne se passe non plus.
J'ai bien le fichier GoogleHome.vbs sur le C:\GoogleHome.

**Comment by jdenieul** [comment]
![image](https://user-images.githubusercontent.com/7125480/44960293-3c835900-aefd-11e8-8353-d19b8930d714.png)

**Comment by ABOATDev** [comment]
Bonsoir,  je règle le problème le plus rapidement possible, le problème est chez moi aussi

**Comment by ABOATDev** [comment]
Télécharger l'archive : https://bayfiles.com/96xaNagaba/assistant-plugins_zip
Et remplacer les 6 fichiers -> http://prntscr.com/kpt38f http://prntscr.com/kpt3pc 
Assistant-plugins a fait une mise a jours

**Comment by jdenieul** [comment]
Bonsoir,

Après avoir remplacé les fichiers, cela ne fonctionne plus du tout.
Pour information, j'ai l'impression qu'il y a quelque chose qui tourne en
boucle, j'ai un fichier 'GoogleHomeNew' qui ne cesse de se créer/supprimer.
Je ne peux donc pas lancer le .vbs pour vérifier que mon paramétrage est OK.



Avant votre mail j'avais réussi a lancer quelques commandes (j'avais mal
configuré ma partie IFFT et n'avais pas saisie ma "key" lors de la 1ère
installation..).


J'espère que ces infos sont utiles pour vous,
Cordialement

**Comment by jdenieul** [comment]
Voici mon adresse mail : j.denieul@gmail.com
